version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: spark_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - spark_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  spark_postgres_data: